// MoistureMLModel.h - auto-generated by scripts/train_logistic_regression.py.
// Regenerate whenever fresh telemetry is available; do not edit by hand.
//
// Feature order (index):
//   0 moisturePct
//   1 temperatureC
//   2 humidityPct
//   3 log1p(luxRaw)
//   4 hoursSinceWater

#pragma once

namespace plantwater {

constexpr int   MOISTURE_ML_HORIZON_HOURS = 6;
constexpr float MOISTURE_ML_THRESHOLD     = 0.50f;

constexpr float MOISTURE_ML_FEATURE_MEAN[5] = {
    45.0f, 21.0f, 55.0f, 6.2f, 30.0f
};
constexpr float MOISTURE_ML_FEATURE_STD[5]  = {
    18.0f,  5.0f, 15.0f, 2.4f, 20.0f
};

// Logistic-regression weights on the standardised features.
constexpr float MOISTURE_ML_COEF[5] = {
    -2.4f,   // moisturePct    -> wetter, less likely
     0.9f,   // temperatureC   -> hotter, more evaporation
    -0.6f,   // humidityPct    -> humid, less evaporation
     0.7f,   // log(lux)       -> sunnier, more transpiration
     1.1f    // hoursSinceWater -> staler, more likely
};
constexpr float MOISTURE_ML_INTERCEPT = -0.35f;

} // namespace plantwater
