"""Train the on-device 'needs water soon' logistic regression.

Usage
-----
    pip install numpy scikit-learn
    python scripts/train_logistic_regression.py                # synthetic data
    python scripts/train_logistic_regression.py --csv data.csv # real telemetry

CSV columns (any order): moisture_pct, temperature_c, humidity_pct, lux,
hours_since_water, needs_water_within_6h (0/1).

Outputs `lib/MoistureML/MoistureMLModel.h` with the standardisation means /
stds, the fitted coefficients, and the decision threshold. The C++ side then
just dot-products + sigmoids at inference time - no runtime ML framework.
"""
from __future__ import annotations

import argparse
import csv
from pathlib import Path

import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score
from sklearn.preprocessing import StandardScaler

HORIZON_HOURS = 6
DECISION_THRESHOLD = 0.50
FEATURES = [
    "moisture_pct",
    "temperature_c",
    "humidity_pct",
    "log1p_lux",
    "hours_since_water",
]
HEADER_PATH = Path("lib/MoistureML/MoistureMLModel.h")


def synthetic_dataset(n: int = 4000, seed: int = 7) -> tuple[np.ndarray, np.ndarray]:
    """Physically-plausible synthetic data. Real ThingSpeak data preferred."""
    rng = np.random.default_rng(seed)
    moisture = np.clip(rng.normal(45, 18, n), 0, 100)
    temperature = np.clip(rng.normal(21, 5, n), 5, 40)
    humidity = np.clip(rng.normal(55, 15, n), 10, 95)
    lux = np.clip(rng.exponential(1500, n), 0, 40000)
    hours = np.clip(rng.exponential(24, n), 0, 200)

    # Physical prior: evaporation stress increases with heat + light + time,
    # decreases with humidity + current moisture. Add noise so it's non-trivial.
    stress = (
        -0.06 * moisture
        + 0.08 * temperature
        - 0.02 * humidity
        + 0.00003 * lux
        + 0.03 * hours
        + rng.normal(0, 0.6, n)
    )
    labels = (stress > stress.mean()).astype(int)

    X = np.column_stack([
        moisture,
        temperature,
        humidity,
        np.log1p(lux),
        hours,
    ])
    return X, labels


def load_csv(path: Path) -> tuple[np.ndarray, np.ndarray]:
    rows = list(csv.DictReader(path.open()))
    if not rows:
        raise SystemExit(f"no rows in {path}")
    X = np.array([
        [
            float(r["moisture_pct"]),
            float(r["temperature_c"]),
            float(r["humidity_pct"]),
            float(np.log1p(float(r["lux"]))),
            float(r["hours_since_water"]),
        ]
        for r in rows
    ])
    y = np.array([int(r["needs_water_within_6h"]) for r in rows])
    return X, y


def emit_header(scaler: StandardScaler, model: LogisticRegression, out: Path) -> None:
    means = scaler.mean_.astype(float)
    stds = scaler.scale_.astype(float)
    coefs = model.coef_[0].astype(float)
    intercept = float(model.intercept_[0])

    fmt = lambda arr: ", ".join(f"{v:.6f}f" for v in arr)

    out.write_text(
        "// MoistureMLModel.h - auto-generated by scripts/train_logistic_regression.py.\n"
        "// Regenerate whenever fresh telemetry is available; do not edit by hand.\n"
        "//\n"
        "// Feature order (index):\n"
        "//   0 moisturePct\n"
        "//   1 temperatureC\n"
        "//   2 humidityPct\n"
        "//   3 log1p(luxRaw)\n"
        "//   4 hoursSinceWater\n\n"
        "#pragma once\n\n"
        "namespace plantwater {\n\n"
        f"constexpr int   MOISTURE_ML_HORIZON_HOURS = {HORIZON_HOURS};\n"
        f"constexpr float MOISTURE_ML_THRESHOLD     = {DECISION_THRESHOLD:.2f}f;\n\n"
        f"constexpr float MOISTURE_ML_FEATURE_MEAN[5] = {{ {fmt(means)} }};\n"
        f"constexpr float MOISTURE_ML_FEATURE_STD[5]  = {{ {fmt(stds)} }};\n\n"
        f"constexpr float MOISTURE_ML_COEF[5] = {{ {fmt(coefs)} }};\n"
        f"constexpr float MOISTURE_ML_INTERCEPT = {intercept:.6f}f;\n\n"
        "} // namespace plantwater\n"
    )


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--csv", type=Path, help="training telemetry CSV")
    ap.add_argument("--out", type=Path, default=HEADER_PATH,
                    help=f"output header path (default {HEADER_PATH})")
    args = ap.parse_args()

    X, y = load_csv(args.csv) if args.csv else synthetic_dataset()

    scaler = StandardScaler().fit(X)
    Xs = scaler.transform(X)

    model = LogisticRegression(max_iter=1000).fit(Xs, y)
    auc = roc_auc_score(y, model.predict_proba(Xs)[:, 1])
    print(f"Train ROC-AUC: {auc:.3f}  (n={len(y)}, positives={int(y.sum())})")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    emit_header(scaler, model, args.out)
    print(f"Wrote {args.out}")


if __name__ == "__main__":
    main()
